from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parent.parent

TEMPLATE = '''"""
{filename}

Auto-generated by Astro Convergence Scaffold.
"""
'''

def create(path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)

    if not path.exists():
        path.write_text(
            TEMPLATE.format(filename=path.name),
            encoding="utf-8"
        )
        print(f"Created {path}")
    else:
        print(f"Exists  {path}")

def main():

    if len(sys.argv) != 2:
        print("Usage:")
        print("python tools/scaffold.py module_name")
        return

    module = sys.argv[1]

    folders = [
        ROOT / module,
        ROOT / "tests"
    ]

    for f in folders:
        f.mkdir(exist_ok=True)

    create(ROOT / module / "__init__.py")
    create(ROOT / module / f"{module}.py")
    create(ROOT / "tests" / f"test_{module}.py")

if __name__ == "__main__":
    main()