"""
Same-run evidence agreement gate (audit finding C-03).

PROJECT_CONSTITUTION.md s12 condition 3 requires that machine-readable
results and a human-readable report be generated BY THE SAME RUN and
agree exactly. `certification_support.emit` satisfies that by deriving the
report from the very dict it serialises, so the two cannot drift apart at
the moment of writing.

This gate defends the property afterwards. A committed report can still be
hand-edited, and an artifact can still be regenerated without its report.
Either would leave two pieces of evidence disagreeing about what was
verified, which is precisely the defect C-03 recorded.

The test therefore re-derives every report from its artifact and demands
byte equality, and a negative control proves the comparison can actually
fail. A gate that cannot fail is not evidence.
"""

import copy
import hashlib
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts"))

import certification_support as support  # noqa: E402

CERTIFICATION = ROOT / "certification"
REPORTS = ROOT / "reports" / "certification"

#: The Tier-0 artifact, named explicitly. Discovery alone would let this
#: gate pass silently on the day the Tier-0 runner stops emitting, which
#: is the exact regression C-03 was.
TIER0_ARTIFACT = "current_engine_certification.json"
TIER0_SLUG = "current_engine"

#: Minimum pairs expected. Guards against a discovery bug turning the
#: whole gate into a no-op.
MINIMUM_PAIRS = 11


def _pairs():
    """Every (artifact, report) pair, matched by the slug emit() records."""

    found = []
    for artifact in sorted(CERTIFICATION.glob("*.json")):
        try:
            data = json.loads(artifact.read_text())
        except json.JSONDecodeError:  # pragma: no cover - malformed artifact
            continue
        if not isinstance(data, dict):
            continue
        slug = data.get("_slug")
        if not slug:
            continue
        report = REPORTS / f"{slug}.report.md"
        found.append((artifact, report, data))
    return found


def test_every_artifact_has_a_report_and_they_agree_byte_for_byte():
    pairs = _pairs()
    assert len(pairs) >= MINIMUM_PAIRS, (
        f"only {len(pairs)} artifact/report pairs discovered, expected at "
        f"least {MINIMUM_PAIRS}; discovery is broken or an emitter regressed"
    )
    for artifact, report, data in pairs:
        assert report.exists(), (
            f"{artifact.name} declares slug {data['_slug']} but "
            f"{report.relative_to(ROOT)} does not exist; the machine-readable "
            "evidence was written without its human-readable counterpart"
        )
        assert support._render(data) == report.read_text(), (
            f"{report.relative_to(ROOT)} does not match what "
            f"{artifact.name} renders to. The two evidence files disagree, so "
            "neither can be trusted. Regenerate by re-running the certifier; "
            "never hand-edit a report."
        )


def test_the_tier0_artifact_is_covered_by_this_gate():
    """C-03 specifically. Named, not merely discovered."""

    artifact = CERTIFICATION / TIER0_ARTIFACT
    report = REPORTS / f"{TIER0_SLUG}.report.md"
    assert artifact.exists(), "Tier-0 machine-readable artifact absent"
    assert report.exists(), (
        "Tier-0 human-readable report absent; PROJECT_CONSTITUTION.md s12 "
        "condition 3 is unmet and the lock is, at most, 'reported'"
    )
    data = json.loads(artifact.read_text())
    assert data.get("_slug") == TIER0_SLUG
    assert support._render(data) == report.read_text()


def test_the_tier0_report_states_the_evidence_contract():
    """Agreement with an empty report would be worthless agreement.

    The report must actually carry the numbers a reader needs in order to
    check the claim, not merely exist and match.
    """

    report = (REPORTS / f"{TIER0_SLUG}.report.md").read_text()
    data = json.loads((CERTIFICATION / TIER0_ARTIFACT).read_text())
    summary = data["summary"]

    for required in (
        "Decision entry:",
        "Tolerance:",
        "source_revision",
        "engine_version",
        "executed_utc",
        "holdout_cases",
        "total_planet_comparisons",
        "total_cusp_comparisons",
        "max_planet_error_arcsec",
        "max_ascendant_error_arcsec",
        "max_cusp_error_arcsec",
        "moshier_fallback_events",
        "result",
    ):
        assert required in report, f"report omits contract field: {required}"

    # The rendered numbers are the artifact's numbers, at full precision.
    assert str(summary["total_planet_comparisons"]) in report
    assert str(summary["max_planet_error_arcsec"]) in report
    assert str(summary["max_cusp_error_arcsec"]) in report
    assert f"**result**: {summary['result']}" in report


@pytest.mark.parametrize(
    "mutate, description",
    [
        (lambda d: d["summary"].__setitem__("result", "FAIL"), "verdict flipped"),
        (
            lambda d: d["summary"].__setitem__("max_planet_error_arcsec", 0.4),
            "numerical maximum altered",
        ),
        (
            lambda d: d["summary"].__setitem__("total_planet_comparisons", 1),
            "comparison count altered",
        ),
        (lambda d: d.__setitem__("tolerance_arcsec", 5.0), "tolerance widened"),
        (
            lambda d: d["run"].__setitem__("source_revision", "0" * 40),
            "source revision altered",
        ),
        (
            lambda d: d["summary"].__setitem__("moshier_fallback_events", 7),
            "fallback count altered",
        ),
    ],
)
def test_negative_control_disagreement_is_detected(mutate, description):
    """The gate must FAIL when the two evidence files disagree.

    The mutation is applied to an in-memory deep copy. Nothing on disk is
    written, and the following test asserts that.
    """

    artifact = CERTIFICATION / TIER0_ARTIFACT
    report = REPORTS / f"{TIER0_SLUG}.report.md"
    corrupted = copy.deepcopy(json.loads(artifact.read_text()))
    mutate(corrupted)
    assert support._render(corrupted) != report.read_text(), (
        f"negative control FAILED: {description} did not change the rendered "
        "report, so the agreement check would not have caught it and its PASS "
        "means nothing"
    )


def test_negative_controls_left_the_evidence_clean():
    """The source implementation and evidence must survive the controls."""

    for path in (
        CERTIFICATION / TIER0_ARTIFACT,
        REPORTS / f"{TIER0_SLUG}.report.md",
        ROOT / "scripts" / "certify_current_engine.py",
        ROOT / "scripts" / "certification_support.py",
    ):
        assert path.exists(), f"{path} vanished during the negative controls"
    # Re-derivation still holds after the controls have run.
    data = json.loads((CERTIFICATION / TIER0_ARTIFACT).read_text())
    assert support._render(data) == (REPORTS / f"{TIER0_SLUG}.report.md").read_text()


def test_render_is_deterministic():
    """Same input, same bytes. Otherwise agreement is untestable."""

    data = json.loads((CERTIFICATION / TIER0_ARTIFACT).read_text())
    first = hashlib.sha256(support._render(data).encode()).hexdigest()
    second = hashlib.sha256(support._render(copy.deepcopy(data)).encode()).hexdigest()
    assert first == second
