"""Shared certification support (ADR-0014 proposed).

Closes four requirements of docs/VALIDATION_STANDARD.md that the
per-layer certification runners did not previously meet:

  s2 rule 4  checksummed data assets verified BEFORE any certification
             run (preflight);
  s2 rule 6  an automated anti-fitting scan is PART OF THE GATE, with
             findings cleared by written justification (scan_for_fitting);
  s1         a "certified/locked" claim requires machine-readable results
             AND a human-readable report generated in the SAME run, with
             console/report agreement (emit);
  s3         the machine-readable results, and the exact console
             transcript, are retained alongside the claim (emit).

Every runner calls preflight() early and emit() last. emit() derives the
human-readable report FROM THE SAME dict it serialises, so the two cannot
disagree by construction.
"""

from __future__ import annotations

import atexit
import hashlib
import io
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

#: Files whose integrity must hold before any certification claim.
CHECKSUM_MANIFEST = ROOT / "CHECKSUMS.sha256"

#: Identifier fragments that would indicate per-case fudging.
_SUSPICIOUS_NAMES = (
    "fudge", "calibrat", "magic_", "hack_", "tweak",
    "correction_for", "offset_for", "adjust_for", "per_case",
)

#: Holdout case identifiers; production code must never mention them.
_HOLDOUT_IDS = re.compile(r"\bH(?:1[01]|[1-9])_[a-z]", re.IGNORECASE)

#: Production code must never import verification-only material.
_FORBIDDEN_IMPORTS = re.compile(
    r"^\s*(?:from|import)\s+(?:jhora|brihat_fixtures|legacy|engine\.tests)\b", re.MULTILINE
)


class CertificationFailure(RuntimeError):
    """Raised when a certification precondition or scan fails."""


def verify_data_assets() -> dict:
    """VALIDATION_STANDARD s2 rule 4: verify checksummed assets."""

    if not CHECKSUM_MANIFEST.exists():
        raise CertificationFailure("CHECKSUMS.sha256 absent; cannot certify")
    verified = {}
    for line in CHECKSUM_MANIFEST.read_text().split("\n"):
        line = line.strip()
        if not line:
            continue
        expected, name = line.split()[0], line.split()[-1]
        target = ROOT / name
        if not target.exists():
            raise CertificationFailure(f"checksummed asset missing: {name}")
        digest = hashlib.sha256(target.read_bytes()).hexdigest()
        if digest != expected:
            raise CertificationFailure(
                f"checksum mismatch for {name}: expected {expected}, got {digest}"
            )
        verified[name] = digest
    if not verified:
        raise CertificationFailure("checksum manifest empty")
    return {"assets_verified": len(verified), "sha256": verified}


def scan_for_fitting(targets=("engine",)) -> dict:
    """
    VALIDATION_STANDARD s2 rule 6: automated anti-fitting scan.

    Flags, in production source only: suspicious identifier fragments;
    any mention of a frozen holdout case identifier; imports of
    verification-only material (the external oracle, transcribed
    fixtures, the legacy kernel, the test package).
    """

    findings = []
    scanned = 0
    for target in targets:
        for path in sorted((ROOT / target).rglob("*.py")):
            if "tests" in path.parts or path.name.startswith("test_"):
                continue
            text = path.read_text()
            scanned += 1
            relative = path.relative_to(ROOT)
            lowered = text.lower()
            for fragment in _SUSPICIOUS_NAMES:
                if fragment in lowered:
                    findings.append({"file": str(relative), "kind": "suspicious_identifier",
                                     "detail": fragment})
            for match in _HOLDOUT_IDS.finditer(text):
                line = text[: match.start()].count("\n") + 1
                findings.append({"file": f"{relative}:{line}", "kind": "holdout_reference",
                                 "detail": match.group(0)})
            for match in _FORBIDDEN_IMPORTS.finditer(text):
                line = text[: match.start()].count("\n") + 1
                findings.append({"file": f"{relative}:{line}", "kind": "verification_import",
                                 "detail": match.group(0).strip()})
    if findings:
        raise CertificationFailure(
            f"anti-fitting scan produced {len(findings)} finding(s), none justified: {findings}"
        )
    return {"modules_scanned": scanned, "findings": [], "justified_exceptions": []}


def _render(report: dict) -> str:
    """Human-readable report derived from the machine-readable dict."""

    lines = [
        f"# {report.get('schema', 'certification')} - HUMAN-READABLE REPORT",
        "",
        "Generated by the same run that produced the machine-readable results, per",
        "docs/VALIDATION_STANDARD.md s1. Do not edit: regenerate.",
        "",
        f"- Decision entry: {report.get('adr', 'n/a')}",
        f"- Date: {report.get('date', 'n/a')}",
        f"- Scope: {report.get('scope', 'n/a')}",
        f"- Result: **{report.get('result', 'n/a')}**",
        "",
    ]
    preconditions = report.get("preconditions")
    if preconditions:
        lines += ["## Preconditions", ""]
        assets = preconditions.get("data_assets", {})
        scan = preconditions.get("anti_fitting", {})
        lines += [
            f"- Data assets verified against CHECKSUMS.sha256: {assets.get('assets_verified')}",
            f"- Anti-fitting scan: {scan.get('modules_scanned')} production modules, "
            f"{len(scan.get('findings', []))} findings",
            "",
        ]
    gates = report.get("gates", {})
    if gates:
        lines += ["## Gates", ""]
        for name, value in gates.items():
            if isinstance(value, dict):
                summary = ", ".join(
                    f"{k}={v}" for k, v in value.items()
                    if isinstance(v, (int, float, str, bool)) and len(str(v)) <= 80
                )
            else:
                summary = str(value)
            lines.append(f"- **{name}**: {summary or 'see machine-readable results'}")
        lines.append("")
    non_claims = report.get("explicit_non_claims")
    if non_claims:
        lines += ["## Explicit non-claims", ""] + [f"- {item}" for item in non_claims] + [""]
    lines += [
        "## Evidence files",
        "",
        f"- machine-readable: `certification/{report.get('_artifact_name', '')}`",
        f"- console transcript: `reports/certification/{report.get('_slug', '')}.console.txt`",
        "",
    ]
    return "\n".join(lines)


class _Tee(io.TextIOBase):
    """Capture stdout while still printing it."""

    def __init__(self, stream):
        self.stream = stream
        self.buffer_text = io.StringIO()

    def write(self, text):
        self.buffer_text.write(text)
        return self.stream.write(text)

    def flush(self):
        self.stream.flush()


def start_transcript() -> _Tee:
    """Begin capturing the console transcript (s3 retention)."""

    tee = _Tee(sys.stdout)
    sys.stdout = tee
    return tee


def preflight() -> dict:
    """Run both mandatory preconditions and return them for the report."""

    return {"data_assets": verify_data_assets(), "anti_fitting": scan_for_fitting()}


def emit(report: dict, artifact_name: str, slug: str, tee=None) -> Path:
    """
    Write the machine-readable artifact, the human-readable report
    derived from the same dict, and the console transcript.
    """

    report["_artifact_name"] = artifact_name
    report["_slug"] = slug
    artifact = ROOT / "certification" / artifact_name
    artifact.write_text(json.dumps(report, indent=1) + "\n")

    reports_dir = ROOT / "reports" / "certification"
    reports_dir.mkdir(parents=True, exist_ok=True)
    (reports_dir / f"{slug}.report.md").write_text(_render(report))

    if tee is not None:
        # Flush at interpreter exit, not here: emit() is called before a
        # runner prints its console summary, and s3 requires the EXACT
        # transcript, which therefore is only complete at exit.
        target = reports_dir / f"{slug}.console.txt"

        def _flush_transcript():
            sys.stdout = tee.stream
            target.write_text(tee.buffer_text.getvalue())

        atexit.register(_flush_transcript)
    return artifact
