"""VARGA_D4_V1 CERTIFICATION RUNNER (ADR-0090).

Certifies the RATIFIED D4 (Chaturthamsa) methodology (ADR-0090 selection
and frozen methodology, `SegmentVargaRule` / `DP-024` Option A2). Per the
owner's "CEO AUTHORIZATION - Execute D16 + D4 Certification Code"
instruction, no production engine module is authorized this task.

**This file is NOT engine/astrology/varga_d4.py and does not create,
modify, or register anything under engine/astrology/varga_registry.py.**
The frozen D4 rule is instantiated here as a standalone, UNREGISTERED
`SegmentVargaRule` object and classified via the already-certified generic
framework (`engine.astrology.varga_classifier.classify`, `engine.astrology.
varga_rules.SegmentVargaRule` - pure functions/dataclasses exercised by D2
and D3, with no registry coupling), mirroring exactly the precedent already
used for D24's own certification-execution stage (ADR-0083) and D40's own
(ADR-0087), before either's own later, separately-authorized production-
implementation task.

**`SegmentVargaRule`, not `CyclicVargaRule`, per the owner's explicit
Option A2 selection** (ADR-0090 section 3): D4's own construction needs a
3-sign step per division, which `CyclicVargaRule`'s `direction` field
cannot express (hard-constrained to +1/-1 - independently reconfirmed live
at drafting time, `DP-032` Part A / `ADR-0090` section 3). This certifier
therefore imports `SegmentVargaRule` only - never `CyclicVargaRule` - and
Gate D below mechanically proves that isolation, plus that
`engine/astrology/varga_rules.py` itself is byte-for-byte unchanged from
its currently-committed content, per the owner's explicit "Do NOT modify
the shared CyclicVargaRule/Cyclic classifier architecture merely to
support D4" instruction.

Regenerates certification/VARGA_D4_V1_certification.json FROM SCRATCH on
every run; the stored JSON is never accepted as proof.

Gates (ADR-0090, DP-033 Part B, mirroring D40's own certification-design
discipline, extended per the owner's explicit isolation instruction; A/B/D/
F/G/H remediated post-audit, see DP-032 addendum):

A table/constant integrity (the frozen 12x4 segment table checked cell by
cell against validate_d4_holdout.py's own independently-typed
REFERENCE_TABLE - not against a shared in-file helper - content-hash
pinned AND ENFORCED, a mismatch fails certification); B dense mathematical
sweep vs validate_d4_holdout.py's own reference_d4(), imported directly -
a genuinely separate implementation (different file, independently typed
kendra-naming lookup, zero shared code with this certifier's own rule
construction); C corroboration disclosure (PyJHora's own published source
was read directly during DP-032 section A.B - see ADR-0090 section 3 - but
cannot be executed in this local environment; genuine oracle execution
remains deferred to this project's own CI hash-pinned oracle environment -
this certification-execution task does NOT wire certify_d4.py into CI);
D isolation, EXTENDED, AND content-hash enforcement (confirms this
certifier touches no existing engine/ file, the standalone rule is never
registered, imports SegmentVargaRule only - never CyclicVargaRule - that
engine/astrology/varga_rules.py's own file content hash is byte-for-byte
unchanged from its currently-committed value, AND FAILS if the frozen
rule's own content hash does not match the pinned value - previously
reported only, now load-bearing); E independent validator
(validate_d4_holdout.py, a from-scratch reimplementation importing nothing
from engine.astrology, run as a genuinely separate subprocess); F boundary
cases (sign-transition edges vs the same imported reference_d4(); the exact
internal division boundaries, empirically confirmed representable with
zero floor-classification effect - ADR-0090 section 3); G protected
holdout (independent SAMPLING of the same imported reference_d4(), never
used to tune the frozen rule); H negative controls (real planted
violations, confirmed detected, including a dedicated control proving the
Gate D hash-enforcement helper itself correctly rejects a mutated rule);
I static independent-reference regression (STATIC values frozen from
validate_d4_holdout.py's own from-scratch reference_d4(), never
regenerated by this certifier's own rule at certification time - retained
as defense-in-depth against future drift in the imported validator itself,
distinct from what A/B/F/G now verify live).

**Post-audit remediation note (DP-032 addendum, 2026-09-04):** gates B, F,
and G previously compared classify() output against an IN-FILE
"_independent_d4_sign()" helper that, on inspection, shared its
kendra-offset content (`_KENDRA_OFFSETS`) with D4_CHATURTHAMSA's own
construction below - meaning those gates verified classify()'s ARITHMETIC
given whatever content that shared constant encoded, but provided NO
protection against a transcription error IN that shared content. An
adversarial audit empirically confirmed this: a planted content mutation
(corrupted kendra-offset tuple) passed gates A, B, C, D, E, F, G, and H
undetected, caught only by gate I's own 10 static points. This revision
removes the self-referential helper entirely and routes gates A, B, F, and
G through validate_d4_holdout.py's own independently-typed reference - the
same file gate E and gate I already trust - closing the gap directly
rather than adding a parallel check.

No third-party computational oracle is used this execution. PyJHora is not
invoked: this project's own local PyJHora environment remains degraded
(numpy import failure, an already-disclosed, unchanged limitation). ADR-0090
section 3 records that PyJHora's own published source (`naturalstupid/
PyJHora`, GitHub) was read directly during DP-032 section A.B and its
default/Traditional-Parasara `chaturthamsa_chart()` method (`f2=3`) matches
this frozen construction exactly - read-only corroboration, not executed
oracle agreement.

Exit code 0 = PASS, 3 = FAIL.
"""

import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

sys.path.insert(0, str(ROOT / "scripts"))
import certification_support as support  # noqa: E402

from engine.astrology.varga_classifier import classify  # noqa: E402
from engine.astrology.varga_rules import SegmentVargaRule, rule_content_sha256  # noqa: E402

#: The genuinely independent reference (DP-032 addendum): a separate file,
#: independently typed (kendra-naming lookup table, not this certifier's
#: own `_KENDRA_OFFSETS` construction), imported directly. Gates A, B, F,
#: and G compare against THIS, not against any in-file helper that shares
#: code with D4_CHATURTHAMSA's own construction below.
import validate_d4_holdout  # noqa: E402

#: Frozen exactly as ADR-0090 section 3 states it: division `l` (0-3) of
#: 0-based source sign `s` maps to target sign `(s + 3*l) mod 12` - the
#: source sign itself, then its 4th, 7th, and 10th houses counted from it
#: (the four kendras). Uniform across all twelve source signs. A standalone
#: object - never registered via
#: engine.astrology.varga_registry.register_varga_rule.
_WIDTH = 30.0 / 4.0
_KENDRA_OFFSETS = (0, 3, 6, 9)

D4_CHATURTHAMSA = SegmentVargaRule(
    segments=tuple(
        tuple((_WIDTH, (source + offset) % 12) for offset in _KENDRA_OFFSETS)
        for source in range(12)
    ),
    division=4,
)

#: Content fingerprint of the frozen rule above, pinned as a literal
#: hardcoded value from a prior intentional run (NOT computed from itself,
#: which would trivially always match and defeat the point of a pin -
#: mirrors scripts/certify_d40.py's own CERTIFIED_D40_CONTENT_SHA256
#: pattern exactly). Computed once via rule_content_sha256(D4_CHATURTHAMSA)
#: and verified independently before being pinned here.
CERTIFIED_D4_CONTENT_SHA256 = (
    "9c5e1a460458fc8348ad8b02c2eecaba65ee77cc4eefa35735c8a548e691a031"
)

#: Content fingerprint of engine/astrology/varga_rules.py itself, captured
#: at the moment this certifier was written (immediately after independently
#: re-verifying, live, that CyclicVargaRule still rejects a step != +-1 -
#: ADR-0090 section 3). Gate D below recomputes this file's hash fresh on
#: every run and fails loudly if it has changed - the mechanical proof that
#: this certification did not modify the shared framework file to make D4
#: fit, per the owner's explicit isolation instruction.
BASELINE_VARGA_RULES_SHA256 = (
    "47ea22a89eb206f0d7da62bf4a1534f5737cd3944bb1b5e57012c6a350030bb7"
)


def fail(message):
    print("D4 CERTIFICATION FAIL:", message)
    sys.exit(3)


def _content_hash_matches(rule) -> bool:
    """The REAL enforcement check (DP-032 addendum, Finding 2): used by both
    gate D (to decide pass/fail - a mismatch now FAILS certification, not
    merely reported) and gate H's own negative control (to prove, against
    this exact function, that a mutated rule is correctly rejected - not a
    separately simulated check)."""

    return rule_content_sha256(rule) == CERTIFIED_D4_CONTENT_SHA256


def gate_a_table_integrity():
    if D4_CHATURTHAMSA.division != 4:
        fail("division != 4")
    for source in range(12):
        segments = D4_CHATURTHAMSA.segments[source]
        if len(segments) != 4:
            fail(f"sign {source}: expected 4 segments")
        for division, (width, target) in enumerate(segments):
            if width != _WIDTH:
                fail(f"sign {source} division {division}: width {width}")
            # DP-032 addendum (Finding 1): checked against validate_d4_holdout.py's
            # own independently-typed reference, not against the shared
            # _KENDRA_OFFSETS constant this rule's own construction also uses -
            # a bug in that constant would previously have gone undetected
            # here. Checked for ALL FOUR divisions, not merely division 0.
            midpoint = division * _WIDTH + _WIDTH / 2.0  # no boundary dust
            expected_sign, expected_division = validate_d4_holdout.reference_d4(
                source * 30.0 + midpoint
            )
            if expected_division != division:
                fail(f"sign {source} division {division}: independent reference "
                     f"midpoint check malformed (got division {expected_division})")
            if target != expected_sign:
                fail(f"sign {source} division {division}: target {target}, "
                     f"independent reference says {expected_sign}")
    return {
        "cells": 48,
        "mismatches": 0,
        "content_sha256": rule_content_sha256(D4_CHATURTHAMSA),
        "verified_against": "validate_d4_holdout.py's own independently-typed "
                             "REFERENCE_TABLE (imported directly) - not a helper "
                             "shared with this rule's own construction",
        "disclosure": "division l (0-3) of source sign s maps to target (s + 3*l) mod 12 - "
                       "the source sign itself, then its 4th, 7th, and 10th houses (the four "
                       "kendras from the source sign), uniform for all twelve source signs - "
                       "Parashara/BPHS, DP-032 section A (ADR-0090 section 3)",
    }


def gate_b_dense_sweep():
    mismatches = 0
    points = 51429
    step = 360.0 / points
    for i in range(points):
        longitude = i * step
        result = classify(longitude, D4_CHATURTHAMSA)
        expected_sign, expected_division = validate_d4_holdout.reference_d4(longitude)
        if (result.d_sign, result.division_index) != (expected_sign, expected_division):
            mismatches += 1
    if mismatches:
        fail(f"dense sweep mismatches: {mismatches}")
    return {"points": points, "mismatches": 0,
            "verified_against": "validate_d4_holdout.reference_d4() (imported directly, "
                                 "a genuinely separate implementation)"}


def gate_c_corroboration_disclosure():
    return {
        "oracle_executed": False,
        "reason": "PyJHora unavailable in this local environment (numpy import failure, "
                  "an already-disclosed, pre-existing limitation) - genuine oracle "
                  "execution deferred to this project's own CI hash-pinned oracle "
                  "environment, per every oracle-tier certifier's own established pattern.",
        "read_only_corroboration": "PyJHora's own published source "
                  "(naturalstupid/PyJHora, GitHub, chaturthamsa_chart(), "
                  "_chaturthamsa_parasara(), f2=3) was read directly during DP-032 "
                  "section A.B (ADR-0090 section 3): its default/Traditional-Parasara "
                  "method (kendra step of 3 signs per division, uniform for all source "
                  "signs) matches this frozen construction exactly. This is read-only "
                  "source inspection, not executed oracle agreement.",
        "classification": "disclosed_gap_not_correctness_evidence",
    }


def gate_d_isolation():
    import ast
    import hashlib
    import inspect

    this_module = sys.modules[__name__]
    own_source = inspect.getsource(this_module)
    tree = ast.parse(own_source)
    forbidden_names = ("varga_d4", "varga_registry", "CyclicVargaRule")
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            module_name = node.module or ""
            imported_names = [alias.name for alias in node.names]
            if "varga_d4" in module_name or "varga_registry" in module_name:
                fail(f"certify_d4.py imports {module_name} - must remain standalone, "
                     f"never touch the registry")
            if "CyclicVargaRule" in imported_names:
                fail("certify_d4.py imports CyclicVargaRule - must remain isolated to "
                     "SegmentVargaRule only, per the owner's explicit isolation instruction")
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if any(name in alias.name for name in forbidden_names):
                    fail(f"certify_d4.py imports {alias.name} - forbidden by isolation")

    if (ROOT / "engine" / "astrology" / "varga_d4.py").exists():
        fail("engine/astrology/varga_d4.py already exists - certification design/"
             "execution does not authorize production implementation")

    # Mechanical proof, not merely a design commitment: the shared framework
    # file this certifier's own CyclicVargaRule-avoidance claim depends on is
    # byte-for-byte unchanged from its currently-committed content.
    varga_rules_path = ROOT / "engine" / "astrology" / "varga_rules.py"
    current_hash = hashlib.sha256(varga_rules_path.read_bytes()).hexdigest()
    if current_hash != BASELINE_VARGA_RULES_SHA256:
        fail(f"engine/astrology/varga_rules.py content changed: {current_hash} != "
             f"baseline {BASELINE_VARGA_RULES_SHA256} - the shared CyclicVargaRule/"
             f"classifier architecture must not be modified to support D4")

    # DP-032 addendum (Finding 2): this check was previously reported only,
    # never enforced - a mismatch would not have stopped certification.
    # Now it does.
    hash_ok = _content_hash_matches(D4_CHATURTHAMSA)
    if not hash_ok:
        fail(f"content hash {rule_content_sha256(D4_CHATURTHAMSA)} does not match "
             f"pinned {CERTIFIED_D4_CONTENT_SHA256} - the frozen rule has changed "
             f"since this pin was computed")

    return {
        "certifier_never_imports_varga_registry_or_varga_d4": True,
        "certifier_never_imports_cyclicvargarule": True,
        "engine_astrology_varga_d4_absent": True,
        "content_sha256_matches_pinned": hash_ok,
        "content_hash_enforcement": "ENFORCED - a mismatch fails this gate, not merely "
                                     "reported (DP-032 addendum, Finding 2)",
        "varga_rules_py_sha256": current_hash,
        "varga_rules_py_unchanged_from_baseline": True,
    }


def gate_e_independent_validator():
    import subprocess
    result = subprocess.run(
        [sys.executable, str(ROOT / "validate_d4_holdout.py")],
        capture_output=True, text=True)
    if result.returncode != 0 or "ALL INDEPENDENT D4 CASES PASSED" not in result.stdout:
        fail(f"independent validator failed: {result.stdout[-1200:]} {result.stderr[-800:]}")
    return {"result": "PASS",
            "classification": "corroborating_correctness_evidence",
            "note": "separate-process, from-scratch reimplementation; does not import "
                    "engine.astrology.varga_classifier, engine.astrology.varga_rules, "
                    "or this certifier's own D4_CHATURTHAMSA object"}


def gate_f_boundary_cases():
    import math
    cases = 0
    mismatches = 0
    for sign in range(12):
        for k in range(1, 4):
            exact_boundary = k * _WIDTH
            cases += 1
            result = classify(sign * 30.0 + exact_boundary, D4_CHATURTHAMSA)
            expected_sign, expected_division = validate_d4_holdout.reference_d4(
                sign * 30.0 + exact_boundary
            )
            if (result.d_sign, result.division_index) != (expected_sign, expected_division):
                mismatches += 1
    for sign in range(12):
        # Mirrors D24/D40/D45's own corrected boundary-probe construction
        # (ADR-0083 gate F): computed at the target magnitude directly, not
        # via an addition that can round away the intended epsilon.
        near_end = classify(math.nextafter((sign + 1) * 30.0, -math.inf), D4_CHATURTHAMSA)
        start = classify(sign * 30.0, D4_CHATURTHAMSA)
        cases += 2
        if near_end.division_index != 3:
            mismatches += 1
        if start.division_index != 0:
            mismatches += 1
    if mismatches:
        fail(f"boundary case failures: {mismatches}/{cases}")
    return {"cases": cases, "mismatches": 0,
            "verified_against": "validate_d4_holdout.reference_d4() (imported directly)",
            "convention": "engine-wide 1e-10 tolerance-promoted boundary convention "
                           "(longitude_utils.py), unmodified; no D4-specific exception - "
                           "cell width 30/4=7.5deg is exactly representable in IEEE-754 "
                           "double precision (ADR-0090 section 3), zero floor-"
                           "classification effect, identical clean result to D24's/D40's own"}


def gate_g_protected_holdout():
    mismatches = 0
    count = 0
    step = 0.0137
    longitude = 0.0
    while longitude < 360.0:
        result = classify(longitude, D4_CHATURTHAMSA)
        expected_sign, expected_division = validate_d4_holdout.reference_d4(longitude)
        if (result.d_sign, result.division_index) != (expected_sign, expected_division):
            mismatches += 1
        count += 1
        longitude += step
    if mismatches:
        fail(f"protected holdout mismatches: {mismatches}")
    return {"points": count, "mismatches": 0,
            "verified_against": "validate_d4_holdout.reference_d4() (imported directly)",
            "methodology": "prime-step deterministic sampling, independent of gate B/F "
                            "points, never used to tune the frozen rule"}


def gate_h_negative_controls():
    from dataclasses import replace

    controls = []

    original_segments = D4_CHATURTHAMSA.segments
    mutated_first = ((_WIDTH, 5),) + original_segments[0][1:]
    mutated = replace(
        D4_CHATURTHAMSA,
        segments=(mutated_first,) + original_segments[1:],
    )
    detected = mutated.segments[0][0] != D4_CHATURTHAMSA.segments[0][0]
    controls.append({"control": "segments[0][0] target mutated 0->5 (wrong value)", "detected": detected})
    if not detected:
        fail("negative control 1 did not detect the planted mutation")

    test_longitude = 30.0 + 10.0  # within Taurus (source=1), division 1
    mutated_result = classify(test_longitude, mutated)
    original_result = classify(test_longitude, D4_CHATURTHAMSA)
    # The mutation only touches source sign 0 (Aries); probe a Taurus point
    # instead to independently confirm mutation on ONE source sign does not
    # silently affect classification of a DIFFERENT, unmutated source sign -
    # then probe Aries itself for the direct detection.
    aries_probe = classify(3.7, mutated)
    aries_original = classify(3.7, D4_CHATURTHAMSA)
    detected_2 = aries_probe.d_sign != aries_original.d_sign
    controls.append({"control": "Aries (mutated source) division 0 target flip detected", "detected": detected_2})
    if not detected_2:
        fail("negative control 2 did not detect the planted mutation")
    unaffected = mutated_result.d_sign == original_result.d_sign and mutated_result.division_index == original_result.division_index
    controls.append({"control": "Taurus (unmutated source) unaffected by Aries-only mutation", "detected": unaffected})
    if not unaffected:
        fail("negative control 2b: mutation to one source sign leaked into another - "
             "the classifier or rule object is not isolating segments per source sign correctly")

    original_hash = rule_content_sha256(D4_CHATURTHAMSA)
    mutated_hash = rule_content_sha256(mutated)
    detected_3 = mutated_hash != original_hash
    controls.append({"control": "content hash changes on mutation", "detected": detected_3})
    if not detected_3:
        fail("negative control 3 did not detect the planted mutation")

    # DP-032 addendum, Finding 2: proves the REAL enforcement path (the exact
    # function gate D calls to decide pass/fail), not a separately simulated
    # comparison. Before this addendum, a hash mismatch was reported but
    # never enforced - this control would have been meaningless without the
    # gate D fix above.
    hash_check_rejects_mutation = not _content_hash_matches(mutated)
    hash_check_accepts_original = _content_hash_matches(D4_CHATURTHAMSA)
    detected_4 = hash_check_rejects_mutation and hash_check_accepts_original
    controls.append({"control": "gate D's own _content_hash_matches() helper rejects the "
                                 "mutated rule and accepts the original", "detected": detected_4})
    if not detected_4:
        fail("negative control 4 did not detect the planted mutation via the real "
             "enforcement helper")

    # DP-032 addendum, Finding 1: proves the NEW independent-reference check
    # (validate_d4_holdout.reference_d4(), imported directly) actually
    # catches a classical-content mutation - the exact failure mode an
    # adversarial audit found gates A/B/F/G previously missed, because they
    # compared against an in-file helper sharing code with the rule's own
    # construction. Corrupts the kendra-offset structure (0,3,6,9 -> 0,4,7,10)
    # across every source sign - a real content error, not a structural one.
    corrupted_offsets = (0, 4, 7, 10)
    content_mutated = replace(
        D4_CHATURTHAMSA,
        segments=tuple(
            tuple((_WIDTH, (source + offset) % 12) for offset in corrupted_offsets)
            for source in range(12)
        ),
    )
    probe_longitude = 30.0 + 10.0  # Taurus (source=1), division 1: kendra 3 -> corrupted to 4
    probe_result = classify(probe_longitude, content_mutated)
    probe_expected_sign, probe_expected_division = validate_d4_holdout.reference_d4(probe_longitude)
    detected_5 = (probe_result.d_sign, probe_result.division_index) != (probe_expected_sign, probe_expected_division)
    controls.append({"control": "corrupted kendra-offset structure (the exact "
                                 "audit-demonstrated content mutation) now disagrees with "
                                 "the independent reference_d4()", "detected": detected_5})
    if not detected_5:
        fail("negative control 5 did not detect the audit-demonstrated content mutation "
             "via the new independent-reference check")

    restored_hash = rule_content_sha256(D4_CHATURTHAMSA)
    if restored_hash != original_hash:
        fail("D4_CHATURTHAMSA itself was mutated - this must never happen (dataclass is frozen)")

    return {"controls": controls, "all_detected": True, "original_object_unmutated": True}


#: Static expected values (D-sign, division index), generated ONCE, offline,
#: from validate_d4_holdout.py's own from-scratch reference_d4() - never by
#: calling this certifier's own D4_CHATURTHAMSA/classify() at certification
#: time. The certification-integrity lesson (ADR-0079), applied from the
#: outset, not retrofitted: comparing LIVE production-style output against
#: values frozen from an independent implementation is genuine cross-
#: implementation agreement, never a self-comparison.
STATIC_HOLDOUT = [
    {"id": "H1_aries_early", "longitude": 3.7, "expected_d_sign": 0, "expected_division_index": 0},
    {"id": "H2_taurus_mid", "longitude": 47.3, "expected_d_sign": 7, "expected_division_index": 2},
    {"id": "H3_gemini_boundary_adjacent", "longitude": 91.25, "expected_d_sign": 3, "expected_division_index": 0},
    {"id": "H4_leo_late", "longitude": 133.9, "expected_d_sign": 7, "expected_division_index": 1},
    {"id": "H5_virgo_exact_division", "longitude": 178.125, "expected_d_sign": 2, "expected_division_index": 3},
    {"id": "H6_libra_mid", "longitude": 200.0, "expected_d_sign": 0, "expected_division_index": 2},
    {"id": "H7_sagittarius_early", "longitude": 259.5, "expected_d_sign": 2, "expected_division_index": 2},
    {"id": "H8_capricorn_mid", "longitude": 289.5, "expected_d_sign": 3, "expected_division_index": 2},
    {"id": "H9_pisces_late", "longitude": 341.9, "expected_d_sign": 2, "expected_division_index": 1},
    {"id": "H10_aries_exact_zero", "longitude": 0.0, "expected_d_sign": 0, "expected_division_index": 0},
]


def gate_i_static_reference_regression():
    cases = 0
    mismatches = 0
    for case in STATIC_HOLDOUT:
        result = classify(case["longitude"], D4_CHATURTHAMSA)
        cases += 1
        if (result.d_sign, result.division_index) != (case["expected_d_sign"], case["expected_division_index"]):
            mismatches += 1
            fail(f"static reference mismatch on {case['id']}: "
                 f"got=({result.d_sign},{result.division_index}) "
                 f"expected=({case['expected_d_sign']},{case['expected_division_index']})")
    return {"cases": cases, "mismatches": 0,
            "methodology": "LIVE certifier output (classify() + the standalone D4_CHATURTHAMSA "
                            "rule) compared against STATIC values frozen from validate_d4_"
                            "holdout.py's own from-scratch reference_d4() (never regenerated "
                            "by this certifier's own rule at certification time)",
            "classification": "correctness_evidence"}


def main():
    tee = support.start_transcript()
    preconditions = support.preflight()
    report = {
        "schema": "varga_d4_v1_certification",
        "adr": "ADR-0090",
        "supersedes_provisional_id": "NOTHING_AUTHORISED",
        "date": str(date.today()),
        "scope": (
            "D4 Chaturthamsa, Parashara/BPHS variant, Traditional Parasara construction. "
            "Rule under certification is a STANDALONE, UNREGISTERED SegmentVargaRule "
            "instance embedded in this certifier - not engine/astrology/varga_d4.py, "
            "no production module is authorized or created this execution. DP-024 "
            "Option A2 (SegmentVargaRule) selected for D4 specifically, per the owner's "
            "explicit instruction - CyclicVargaRule is untouched."
        ),
        "rule": {
            "kind": "standalone SegmentVargaRule instance embedded in this certifier "
                    "(scripts/certify_d4.py) - not a registered production rule",
            "divisions": 4,
            "school": "parashara",
            "construction": "division l (0-3) of source sign s maps to target (s + 3*l) "
                             "mod 12 - the four kendras from the source sign, uniform for "
                             "all twelve source signs",
            "content_sha256": rule_content_sha256(D4_CHATURTHAMSA),
        },
        "oracle": gate_c_corroboration_disclosure(),
        "gates": {
            "A_table_integrity": gate_a_table_integrity(),
            "B_dense_sweep": gate_b_dense_sweep(),
            "C_corroboration_disclosure": gate_c_corroboration_disclosure(),
            "D_isolation": gate_d_isolation(),
            "E_independent_validator": gate_e_independent_validator(),
            "F_boundary_cases": gate_f_boundary_cases(),
            "G_protected_holdout": gate_g_protected_holdout(),
            "H_negative_controls": gate_h_negative_controls(),
            "I_static_reference_regression": gate_i_static_reference_regression(),
        },
        "explicit_non_claims": [
            "no oracle execution this run - PyJHora unavailable locally, deferred to CI; "
            "certify_d4.py is NOT wired into .github/workflows/ci.yml's oracle-tier "
            "loop by this certification-execution task - that remains a separate, "
            "not-yet-authorized act",
            "any per-division deity/label payload (VargaClassification carries only "
            "D-sign, division index, and fraction; deity output is out of scope, "
            "mirroring D16/D24/D40/D45's own identical treatment - ADR-0090 section 4; "
            "DP-032 section A.H first disclosed D4's own four-Kumara deity payload)",
            "the three non-default PyJHora chart_method variants (Parivritti Cyclic, "
            "Parivritti Even Reverse, Somanatha Parivritti Alternate) - excluded, "
            "mirroring D24's own two and D45's own three excluded PyJHora methods",
            "any non-parashara school variant",
            "any other varga; each requires its own ADR and certification",
            "no engine/ production module is created or modified by this certification",
            "no change of any kind to engine/astrology/varga_rules.py or "
            "varga_classifier.py - DP-024 Option A1 (the step field) is NOT "
            "implemented by this certification, mechanically verified by Gate D",
            "paraphrase-only caveat: the BPHS citation is corroborated by consistent "
            "modern paraphrase across independent sources, not a located verbatim "
            "Sanskrit verse/Sarga-and-Shloka citation (ADR-0090 section 3, DP-032 "
            "section A.B)",
        ],
        "environment": {"python": sys.version.split()[0]},
        "preconditions": preconditions,
        "result": "PASS",
    }
    out = support.emit(report, "VARGA_D4_V1_certification.json", "varga_d4", tee)
    print("=" * 60)
    print("VARGA_D4_V1 CERTIFICATION (standalone rule, not production-registered)")
    print("=" * 60)
    for name, gate in report["gates"].items():
        print(f"{name}: {gate}")
    print("archived          :", out.relative_to(ROOT).as_posix())
    print("RESULT            : PASS")


if __name__ == "__main__":
    main()
