"""VARGA_D16_V1 CERTIFICATION RUNNER (ADR-0089).

Certifies the RATIFIED D16 (Shodasamsa) methodology (ADR-0089 selection and
frozen methodology). Per the owner's "CEO AUTHORIZATION - Execute D16 + D4
Certification Code" instruction, no production engine module is authorized
this task.

**This file is NOT engine/astrology/varga_d16.py and does not create,
modify, or register anything under engine/astrology/varga_registry.py.**
The frozen D16 rule is instantiated here as a standalone, UNREGISTERED
`CyclicVargaRule` object and classified via the already-certified generic
framework (`engine.astrology.varga_classifier.classify`, `engine.astrology.
varga_rules.CyclicVargaRule` - pure functions/dataclasses exercised by
eight already-certified vargas, D2/D3/D7/D12/D24/D30/D40/D45, with no
registry coupling), mirroring exactly the precedent already used for D24's
own certification-execution stage (ADR-0083) and D40's own (ADR-0087),
before either's own later, separately-authorized production-implementation
task.

Regenerates certification/VARGA_D16_V1_certification.json FROM SCRATCH on
every run; the stored JSON is never accepted as proof.

Gates (ADR-0089, DP-033 Part A, mirroring D40's own certification-design
discipline; A/B/D/F/G/H remediated post-audit, see DP-032 addendum):

A table/constant integrity (the frozen start_sign/direction table checked
cell by cell against validate_d16_holdout.py's own independently-typed
REFERENCE_TABLE - not against a shared in-file helper - content-hash
pinned AND ENFORCED, a mismatch fails certification); B dense mathematical
sweep vs validate_d16_holdout.py's own reference_d16(), imported directly -
a genuinely separate implementation (different file, independently typed
sign-name lookup table, zero shared code with this certifier's own rule
construction); C CONDITIONAL-GENUINE ORACLE (CI-wiring authorization
2026-09-08): a real PyJHora shodasamsa_chart(chart_method=1) comparison at
zero categorical tolerance whenever PyJHora is importable - which it is in
this project's own CI hash-pinned oracle job, into which certify_d16.py is
now wired - and disclosure-only on a host where it is not, such as this
Windows one. The gate never blocks gate D and never fails on the disclosure
branch, but a GENUINE mismatch fails certification at the end of main(); D isolation AND content-hash enforcement (confirms this
certifier touches no existing engine/ file, the standalone rule is never
registered, and FAILS if the frozen rule's content hash does not match the
pinned value - previously reported only, now load-bearing); E independent
validator (validate_d16_holdout.py, a from-scratch reimplementation
importing nothing from engine.astrology, run as a genuinely separate
subprocess); F boundary cases (sign-transition edges vs the same imported
reference_d16(); the exact internal division boundaries, empirically
confirmed representable with zero floor-classification effect - ADR-0089
section 3); G protected holdout (independent SAMPLING of the same imported
reference_d16(), never used to tune the frozen rule); H negative controls
(real planted violations, confirmed detected, including a dedicated control
proving the Gate D hash-enforcement helper itself correctly rejects a
mutated rule - not merely that hashes differ); I static independent-
reference regression (STATIC values frozen from validate_d16_holdout.py's
own from-scratch reference_d16(), never regenerated by this certifier's
own rule at certification time - retained as defense-in-depth against
future drift in the imported validator itself, distinct from what A/B/F/G
now verify live).

**Post-audit remediation note (DP-032 addendum, 2026-09-04):** gates B, F,
and G previously compared classify() output against an IN-FILE
"_independent_d16_sign()" helper that, on inspection, shared its
start-sign content (`_start_for_source()`) with D16_SHODASAMSA's own
construction below - meaning those gates verified classify()'s ARITHMETIC
given whatever content that shared helper encoded, but provided NO
protection against a transcription error IN that shared content. An
adversarial audit empirically confirmed this: a planted content mutation
(fixed/dual start-sign swap) passed gates A, B, C, D, E, F, G, and H
undetected, caught only by gate I's own 10 static points. This revision
removes the self-referential helper entirely and routes gates A, B, F, and
G through validate_d16_holdout.py's own independently-typed reference -
the same file gate E and gate I already trust - closing the gap directly
rather than adding a parallel check.

Whether a third-party computational oracle is used depends on the
environment, and the artifact records which happened rather than asserting
one. On this Windows host PyJHora remains unimportable (numpy import
failure, an already-disclosed, unchanged limitation) and gate C emits its
disclosure branch; in CI's hash-pinned oracle environment PyJHora is
present and gate C performs 5,400 genuine comparisons. ADR-0089 section 3
separately records that PyJHora's own published source (`naturalstupid/
PyJHora`, GitHub) was read directly during DP-032 section B.B and its
default/Traditional-Parasara `shodasamsa_chart()` method matches this
frozen construction exactly - that remains read-only corroboration, and is
never presented as executed oracle agreement.

Exit code 0 = PASS, 3 = FAIL.
"""

import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

sys.path.insert(0, str(ROOT / "scripts"))
import certification_support as support  # noqa: E402

from engine.astrology.varga_classifier import classify  # noqa: E402
from engine.astrology.varga_rules import CyclicVargaRule, rule_content_sha256  # noqa: E402

#: The genuinely independent reference (DP-032 addendum): a separate file,
#: independently typed (sign-name lookup table, not this certifier's own
#: integer-set/`_start_for_source()` construction), imported directly.
#: Gates A, B, F, and G compare against THIS, not against any in-file
#: helper that shares code with D16_SHODASAMSA's own construction below.
import validate_d16_holdout  # noqa: E402

#: Frozen exactly as ADR-0089 section 3 states it: movable source signs
#: (0-based Aries=0, Cancer=3, Libra=6, Capricorn=9) start from Aries
#: (index 0); fixed source signs (Taurus=1, Leo=4, Scorpio=7, Aquarius=10)
#: start from Leo (index 4); dual source signs (Gemini=2, Virgo=5,
#: Sagittarius=8, Pisces=11) start from Sagittarius (index 8); forward
#: counting (direction +1) for all twelve. A standalone object - never
#: registered via engine.astrology.varga_registry.register_varga_rule.
_MOVABLE_SOURCE_SIGNS = frozenset({0, 3, 6, 9})
_FIXED_SOURCE_SIGNS = frozenset({1, 4, 7, 10})
_ARIES, _LEO, _SAGITTARIUS = 0, 4, 8


def _start_for_source(source_sign: int) -> int:
    if source_sign in _MOVABLE_SOURCE_SIGNS:
        return _ARIES
    if source_sign in _FIXED_SOURCE_SIGNS:
        return _LEO
    return _SAGITTARIUS


D16_SHODASAMSA = CyclicVargaRule(
    divisions=16,
    start_sign=tuple(_start_for_source(s) for s in range(12)),
    direction=(1,) * 12,
)

#: Content fingerprint of the frozen rule above, pinned as a literal
#: hardcoded value from a prior intentional run (NOT computed from itself,
#: which would trivially always match and defeat the point of a pin -
#: mirrors scripts/certify_d40.py's own CERTIFIED_D40_CONTENT_SHA256
#: pattern exactly). Computed once via rule_content_sha256(D16_SHODASAMSA)
#: and verified independently before being pinned here.
CERTIFIED_D16_CONTENT_SHA256 = (
    "e86961e430114ba472c7def37e71a23a0761bd06531ef13b44a7716106072e48"
)


def fail(message):
    print("D16 CERTIFICATION FAIL:", message)
    sys.exit(3)


def _content_hash_matches(rule) -> bool:
    """The REAL enforcement check (DP-032 addendum, Finding 2): used by both
    gate D (to decide pass/fail - a mismatch now FAILS certification, not
    merely reported) and gate H's own negative control (to prove, against
    this exact function, that a mutated rule is correctly rejected - not a
    separately simulated check)."""

    return rule_content_sha256(rule) == CERTIFIED_D16_CONTENT_SHA256


def gate_a_table_integrity():
    if D16_SHODASAMSA.divisions != 16:
        fail("divisions != 16")
    for source in range(12):
        # DP-032 addendum (Finding 1): checked against validate_d16_holdout.py's
        # own independently-typed reference, not against the shared
        # _start_for_source() helper this rule's own construction also uses -
        # a bug in that helper would previously have gone undetected here.
        midpoint_degree = (30.0 / 16.0) / 2.0  # division 0's midpoint, no boundary dust
        expected_sign, expected_division = validate_d16_holdout.reference_d16(
            source * 30.0 + midpoint_degree
        )
        if expected_division != 0:
            fail(f"sign {source}: independent reference division-0 check malformed")
        if D16_SHODASAMSA.start_sign[source] != expected_sign:
            fail(f"sign {source}: start {D16_SHODASAMSA.start_sign[source]}, "
                 f"independent reference says {expected_sign}")
        if D16_SHODASAMSA.direction[source] != 1:
            fail(f"sign {source}: direction")
    return {
        "cells": 12,
        "mismatches": 0,
        "content_sha256": rule_content_sha256(D16_SHODASAMSA),
        "verified_against": "validate_d16_holdout.py's own independently-typed "
                             "REFERENCE_TABLE (imported directly) - not a helper "
                             "shared with this rule's own construction",
        "disclosure": "movable source signs (0-based 0,3,6,9) start Aries (index 0); "
                       "fixed source signs (1,4,7,10) start Leo (index 4); "
                       "dual source signs (2,5,8,11) start Sagittarius (index 8); "
                       "forward counting for all twelve - Parashara/BPHS, DP-032 section B "
                       "(ADR-0089 section 3)",
    }


def gate_b_dense_sweep():
    mismatches = 0
    points = 51429
    step = 360.0 / points
    for i in range(points):
        longitude = i * step
        result = classify(longitude, D16_SHODASAMSA)
        expected_sign, expected_division = validate_d16_holdout.reference_d16(longitude)
        if (result.d_sign, result.division_index) != (expected_sign, expected_division):
            mismatches += 1
    if mismatches:
        fail(f"dense sweep mismatches: {mismatches}")
    return {"points": points, "mismatches": 0,
            "verified_against": "validate_d16_holdout.reference_d16() (imported directly, "
                                 "a genuinely separate implementation)"}


#: Set by gate_c_oracle() when a GENUINE PyJHora comparison actually runs.
#: main() fails on a nonzero value at the END, after every other gate has
#: produced its evidence - see the ordering note in main().
_ORACLE_MISMATCHES = 0
PYJHORA_VERSION = None


def gate_c_oracle():
    """Genuine external-oracle gate when PyJHora is importable; disclosure-only
    when it is not (CI-wiring authorization 2026-09-08).

    Replaces the previous unconditional gate_c_corroboration_disclosure(),
    which hard-coded "PyJHora unavailable in this local environment". That text
    was true of this Windows host and false of CI's hash-pinned oracle job,
    where PyJHora demonstrably IS available - so wiring this certifier into
    that job without this change would have made the artifact assert a
    falsehood. Nothing is weakened: before this change no oracle comparison
    ran at all, in any environment.

    NON-BLOCKING, following D20's ratified construction (owner's DP-036
    decision 2): this function never calls fail() for a mismatch, and main()
    evaluates gate D_isolation BEFORE it, so that gate stays reachable on a
    host without PyJHora - the exact defect DP-032's D24/D40 audit found in
    certify_d24's ordering. A genuine mismatch still fails certification, at
    the end of main().

    Oracle: PyJHora's shodasamsa_chart, Traditional Parasara (chart_method=1), at ZERO
    categorical tolerance - D16 is pure longitude arithmetic with no
    astronomical component, so no tolerance derivation applies."""

    global _ORACLE_MISMATCHES, PYJHORA_VERSION

    try:
        import jhora  # noqa: F401
        import importlib.metadata
        PYJHORA_VERSION = importlib.metadata.version("PyJHora")
    except Exception as error:
        return _gate_c_disclosure(str(error))

    # PyJHora IS importable here. From this point a missing entry point or a
    # changed calling interface is a REAL failure, never a silent fall-back to
    # the disclosure branch: a mistyped function name must not be able to
    # masquerade as "the oracle was unavailable" and leave a plausible-looking
    # artifact behind. This is deliberately stricter than the blanket
    # try/except that certify_d20.py's own gate C uses.
    try:
        from jhora.horoscope.chart.charts import shodasamsa_chart
    except Exception as error:
        fail(f"PyJHora {PYJHORA_VERSION} is installed but shodasamsa_chart could not be "
             f"imported ({error}) - that is an oracle-interface defect, not an "
             f"unavailable oracle, and must not be disclosed away")

    mismatches = 0
    comparisons = 0
    per_sign = 450
    for source in range(12):
        for i in range(per_sign):
            within = (i + 0.5) * (30.0 / per_sign)  # midpoints, no boundary dust
            oracle = shodasamsa_chart([["L", (source, within)]], chart_method=1)
            oracle_sign = oracle[0][1][0]
            ours = classify(source * 30.0 + within, D16_SHODASAMSA)
            if ours.d_sign != oracle_sign:
                mismatches += 1
            comparisons += 1
    _ORACLE_MISMATCHES = mismatches
    return {
        "oracle_executed": True,
        "execution_tier": "CI hash-pinned oracle environment (requirements-oracle.lock)",
        "blocking": False,
        "blocking_rationale": "gate D_isolation is evaluated first and this gate never "
                               "calls fail() for a mismatch; a genuine disagreement is "
                               "failed on at the end of main(), after every gate has "
                               "produced its evidence (D20/DP-036 decision 2 pattern).",
        "package": "PyJHora",
        "version": PYJHORA_VERSION,
        "function": "shodasamsa_chart(chart_method=1, Traditional Parasara)",
        "tolerance": "zero categorical tolerance - pure longitude arithmetic, no "
                      "astronomy, so no tolerance derivation applies",
        "comparisons": comparisons,
        "mismatches": mismatches,
        "classification": "genuine_external_oracle_agreement" if not mismatches
                           else "genuine_external_oracle_MISMATCH",
    }


def _gate_c_disclosure(error_text):
    """Disclosure-only result, used when PyJHora cannot be imported at all.
    Never presented as oracle verification (NEW_VARGA_IMPLEMENTATION_TEMPLATE
    v1.1.0 requirement F)."""

    return {
        "oracle_executed": False,
        "blocking": False,
        "reason": f"PyJHora unavailable in this environment ({error_text}) - the "
                  f"documented, pre-existing Windows/Linux gate-parity limitation "
                  f"(.claude/rules/certification.md). Genuine oracle execution is "
                  f"deferred to this project's own CI hash-pinned oracle environment, "
                  f"into which this certifier is now wired.",
        "read_only_corroboration": "PyJHora's own published source "
                  "(naturalstupid/PyJHora, GitHub, shodasamsa_chart()) was read "
                  "directly during DP-032 section B.B (ADR-0089 section 3): its default/"
                  "Traditional-Parasara method (movable=Aries(0), fixed=Leo(4), "
                  "dual=Sagittarius(8), forward) matches this frozen construction "
                  "exactly. This is read-only source inspection, not executed oracle "
                  "agreement.",
        "classification": "disclosed_gap_not_correctness_evidence",
        "if_executed_tolerance": "zero categorical tolerance - D16 is pure longitude "
                                  "arithmetic with no astronomical component, so no "
                                  "tolerance derivation applies",
    }


def gate_d_isolation():
    import ast
    import inspect

    this_module = sys.modules[__name__]
    own_source = inspect.getsource(this_module)
    tree = ast.parse(own_source)
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            module_name = getattr(node, "module", None) or (
                node.names[0].name if isinstance(node, ast.Import) else None
            )
            if module_name and (
                "varga_d16" in module_name or "varga_registry" in module_name
            ):
                fail(f"certify_d16.py imports {module_name} - must remain standalone, "
                     f"never touch the registry")

    if not (ROOT / "engine" / "astrology" / "varga_d16.py").exists():
        registered = True
    else:
        fail("engine/astrology/varga_d16.py already exists - certification design/"
             "execution does not authorize production implementation")

    # DP-032 addendum (Finding 2): this check was previously reported only,
    # never enforced - a mismatch would not have stopped certification.
    # Now it does.
    hash_ok = _content_hash_matches(D16_SHODASAMSA)
    if not hash_ok:
        fail(f"content hash {rule_content_sha256(D16_SHODASAMSA)} does not match "
             f"pinned {CERTIFIED_D16_CONTENT_SHA256} - the frozen rule has changed "
             f"since this pin was computed")

    return {
        "certifier_never_imports_varga_registry_or_varga_d16": True,
        "engine_astrology_varga_d16_absent": registered,
        "content_sha256_matches_pinned": hash_ok,
        "content_hash_enforcement": "ENFORCED - a mismatch fails this gate, not merely "
                                     "reported (DP-032 addendum, Finding 2)",
    }


def gate_e_independent_validator():
    import subprocess
    result = subprocess.run(
        [sys.executable, str(ROOT / "validate_d16_holdout.py")],
        capture_output=True, text=True)
    if result.returncode != 0 or "ALL INDEPENDENT D16 CASES PASSED" not in result.stdout:
        fail(f"independent validator failed: {result.stdout[-1200:]} {result.stderr[-800:]}")
    return {"result": "PASS",
            "classification": "corroborating_correctness_evidence",
            "note": "separate-process, from-scratch reimplementation; does not import "
                    "engine.astrology.varga_classifier, engine.astrology.varga_rules, "
                    "or this certifier's own D16_SHODASAMSA object"}


def gate_f_boundary_cases():
    import math
    cases = 0
    mismatches = 0
    width = 30.0 / 16.0
    for sign in range(12):
        for k in range(1, 16):
            exact_boundary = k * width
            cases += 1
            result = classify(sign * 30.0 + exact_boundary, D16_SHODASAMSA)
            expected_sign, expected_division = validate_d16_holdout.reference_d16(
                sign * 30.0 + exact_boundary
            )
            if (result.d_sign, result.division_index) != (expected_sign, expected_division):
                mismatches += 1
    for sign in range(12):
        # Mirrors D24/D40/D45's own corrected boundary-probe construction
        # (ADR-0083 gate F): computed at the target magnitude directly, not
        # via an addition that can round away the intended epsilon.
        near_end = classify(math.nextafter((sign + 1) * 30.0, -math.inf), D16_SHODASAMSA)
        start = classify(sign * 30.0, D16_SHODASAMSA)
        cases += 2
        if near_end.division_index != 15:
            mismatches += 1
        if start.division_index != 0:
            mismatches += 1
    if mismatches:
        fail(f"boundary case failures: {mismatches}/{cases}")
    return {"cases": cases, "mismatches": 0,
            "verified_against": "validate_d16_holdout.reference_d16() (imported directly)",
            "convention": "engine-wide 1e-10 tolerance-promoted boundary convention "
                           "(longitude_utils.py), unmodified; no D16-specific exception - "
                           "cell width 30/16=1.875deg is exactly representable in IEEE-754 "
                           "double precision (ADR-0089 section 3), zero floor-"
                           "classification effect, identical clean result to D24's/D40's own"}


def gate_g_protected_holdout():
    mismatches = 0
    count = 0
    step = 0.0137
    longitude = 0.0
    while longitude < 360.0:
        result = classify(longitude, D16_SHODASAMSA)
        expected_sign, expected_division = validate_d16_holdout.reference_d16(longitude)
        if (result.d_sign, result.division_index) != (expected_sign, expected_division):
            mismatches += 1
        count += 1
        longitude += step
    if mismatches:
        fail(f"protected holdout mismatches: {mismatches}")
    return {"points": count, "mismatches": 0,
            "verified_against": "validate_d16_holdout.reference_d16() (imported directly)",
            "methodology": "prime-step deterministic sampling, independent of gate B/F "
                            "points, never used to tune the frozen rule"}


def gate_h_negative_controls():
    from dataclasses import replace

    controls = []

    mutated = replace(D16_SHODASAMSA, start_sign=(1,) + D16_SHODASAMSA.start_sign[1:])
    detected = mutated.start_sign[0] != D16_SHODASAMSA.start_sign[0]
    controls.append({"control": "start_sign[0] mutated Aries->wrong value", "detected": detected})
    if not detected:
        fail("negative control 1 did not detect the planted mutation")

    mutated_dir = replace(
        D16_SHODASAMSA,
        direction=D16_SHODASAMSA.direction[:1] + (-1,) + D16_SHODASAMSA.direction[2:],
    )
    test_longitude = 30.0 + 7.0  # within Taurus (fixed, source=1), segment index != multiple of 12
    mutated_result = classify(test_longitude, mutated_dir)
    original_result = classify(test_longitude, D16_SHODASAMSA)
    detected_2 = mutated_result.d_sign != original_result.d_sign
    controls.append({"control": "direction[1] mutated +1->-1", "detected": detected_2})
    if not detected_2:
        fail("negative control 2 did not detect the planted mutation")

    original_hash = rule_content_sha256(D16_SHODASAMSA)
    mutated_hash = rule_content_sha256(mutated)
    detected_3 = mutated_hash != original_hash
    controls.append({"control": "content hash changes on mutation", "detected": detected_3})
    if not detected_3:
        fail("negative control 3 did not detect the planted mutation")

    # DP-032 addendum, Finding 2: proves the REAL enforcement path (the exact
    # function gate D calls to decide pass/fail), not a separately simulated
    # comparison. Before this addendum, a hash mismatch was reported but
    # never enforced - this control would have been meaningless without the
    # gate D fix above.
    hash_check_rejects_mutation = not _content_hash_matches(mutated)
    hash_check_accepts_original = _content_hash_matches(D16_SHODASAMSA)
    detected_4 = hash_check_rejects_mutation and hash_check_accepts_original
    controls.append({"control": "gate D's own _content_hash_matches() helper rejects the "
                                 "mutated rule and accepts the original", "detected": detected_4})
    if not detected_4:
        fail("negative control 4 did not detect the planted mutation via the real "
             "enforcement helper")

    # DP-032 addendum, Finding 1: proves the NEW independent-reference check
    # (validate_d16_holdout.reference_d16(), imported directly) actually
    # catches a classical-content mutation - the exact failure mode an
    # adversarial audit found gates A/B/F/G previously missed, because they
    # compared against an in-file helper sharing code with the rule's own
    # construction. Swaps which start sign the fixed/dual triplicities use -
    # a real content error, not a structural one.
    content_mutated = replace(
        D16_SHODASAMSA,
        start_sign=tuple(
            _SAGITTARIUS if D16_SHODASAMSA.start_sign[s] == _LEO
            else _LEO if D16_SHODASAMSA.start_sign[s] == _SAGITTARIUS
            else D16_SHODASAMSA.start_sign[s]
            for s in range(12)
        ),
    )
    probe_longitude = 30.0 + 7.3  # Taurus (fixed, source=1): start Leo -> mutated to Sagittarius
    probe_result = classify(probe_longitude, content_mutated)
    probe_expected_sign, probe_expected_division = validate_d16_holdout.reference_d16(probe_longitude)
    detected_5 = (probe_result.d_sign, probe_result.division_index) != (probe_expected_sign, probe_expected_division)
    controls.append({"control": "fixed/dual start-sign swap (the exact audit-demonstrated "
                                 "content mutation) now disagrees with the independent "
                                 "reference_d16()", "detected": detected_5})
    if not detected_5:
        fail("negative control 5 did not detect the audit-demonstrated content mutation "
             "via the new independent-reference check")

    restored_hash = rule_content_sha256(D16_SHODASAMSA)
    if restored_hash != original_hash:
        fail("D16_SHODASAMSA itself was mutated - this must never happen (dataclass is frozen)")

    return {"controls": controls, "all_detected": True, "original_object_unmutated": True}


#: Static expected values (D-sign, division index), generated ONCE, offline,
#: from validate_d16_holdout.py's own from-scratch reference_d16() - never
#: by calling this certifier's own D16_SHODASAMSA/classify() at certification
#: time. The certification-integrity lesson (ADR-0079), applied from the
#: outset, not retrofitted: comparing LIVE production-style output against
#: values frozen from an independent implementation is genuine cross-
#: implementation agreement, never a self-comparison.
STATIC_HOLDOUT = [
    {"id": "H1_aries_early", "longitude": 3.7, "expected_d_sign": 1, "expected_division_index": 1},
    {"id": "H2_taurus_mid", "longitude": 47.3, "expected_d_sign": 1, "expected_division_index": 9},
    {"id": "H3_gemini_boundary_adjacent", "longitude": 91.25, "expected_d_sign": 0, "expected_division_index": 0},
    {"id": "H4_leo_late", "longitude": 133.9, "expected_d_sign": 11, "expected_division_index": 7},
    {"id": "H5_virgo_exact_division", "longitude": 178.125, "expected_d_sign": 11, "expected_division_index": 15},
    {"id": "H6_libra_mid", "longitude": 200.0, "expected_d_sign": 10, "expected_division_index": 10},
    {"id": "H7_sagittarius_early", "longitude": 259.5, "expected_d_sign": 6, "expected_division_index": 10},
    {"id": "H8_capricorn_mid", "longitude": 289.5, "expected_d_sign": 10, "expected_division_index": 10},
    {"id": "H9_pisces_late", "longitude": 341.9, "expected_d_sign": 2, "expected_division_index": 6},
    {"id": "H10_aries_exact_zero", "longitude": 0.0, "expected_d_sign": 0, "expected_division_index": 0},
]


def gate_i_static_reference_regression():
    cases = 0
    mismatches = 0
    for case in STATIC_HOLDOUT:
        result = classify(case["longitude"], D16_SHODASAMSA)
        cases += 1
        if (result.d_sign, result.division_index) != (case["expected_d_sign"], case["expected_division_index"]):
            mismatches += 1
            fail(f"static reference mismatch on {case['id']}: "
                 f"got=({result.d_sign},{result.division_index}) "
                 f"expected=({case['expected_d_sign']},{case['expected_division_index']})")
    return {"cases": cases, "mismatches": 0,
            "methodology": "LIVE certifier output (classify() + the standalone D16_SHODASAMSA "
                            "rule) compared against STATIC values frozen from validate_d16_"
                            "holdout.py's own from-scratch reference_d16() (never regenerated "
                            "by this certifier's own rule at certification time)",
            "classification": "correctness_evidence"}


def main():
    tee = support.start_transcript()
    preconditions = support.preflight()
    # CI-WIRING 2026-09-08, following D20's ratified construction (owner's
    # DP-036 decision 2): gate D_isolation is evaluated BEFORE gate C, so the
    # oracle can never prevent it from running - the exact defect DP-032's
    # D24/D40 audit found in certify_d24's ordering. The reported dict below is
    # still ordered A..I; only evaluation order differs. gate_c_oracle() is
    # called ONCE and its single result reused for both the "oracle" and
    # "gates" keys (it previously ran twice, which a genuine 5,400-comparison
    # oracle run must not do).
    _a = gate_a_table_integrity()
    _b = gate_b_dense_sweep()
    _d = gate_d_isolation()          # <- before C, deliberately
    _e = gate_e_independent_validator()
    _f = gate_f_boundary_cases()
    _g = gate_g_protected_holdout()
    _h = gate_h_negative_controls()
    _i = gate_i_static_reference_regression()
    _c = gate_c_oracle()          # <- last; never fails on a mismatch itself
    report = {
        "schema": "varga_d16_v1_certification",
        "adr": "ADR-0089",
        "supersedes_provisional_id": "NOTHING_AUTHORISED",
        "date": str(date.today()),
        "scope": (
            "D16 Shodasamsa, Parashara/BPHS variant, Traditional Parasara construction. "
            "Rule under certification is a STANDALONE, UNREGISTERED CyclicVargaRule "
            "instance embedded in this certifier - not engine/astrology/varga_d16.py, "
            "no production module is authorized or created this execution."
        ),
        "rule": {
            "kind": "standalone CyclicVargaRule instance embedded in this certifier "
                    "(scripts/certify_d16.py) - not a registered production rule",
            "divisions": 16,
            "school": "parashara",
            "construction": "movable source signs start Aries (index 0), fixed source signs "
                             "start Leo (index 4), dual source signs start Sagittarius "
                             "(index 8), forward counting for all twelve",
            "content_sha256": rule_content_sha256(D16_SHODASAMSA),
        },
        "oracle": _c,
        "gates": {
            "A_table_integrity": _a,
            "B_dense_sweep": _b,
            "C_oracle": _c,
            "D_isolation": _d,
            "E_independent_validator": _e,
            "F_boundary_cases": _f,
            "G_protected_holdout": _g,
            "H_negative_controls": _h,
            "I_static_reference_regression": _i,
        },
        "explicit_non_claims": [
            "oracle execution is conditional: a GENUINE PyJHora comparison when the "
            "library is importable (CI's hash-pinned oracle job, into which "
            "certify_d16.py is now wired), disclosure-only otherwise. The gates block "
            "records which of the two actually happened - a disclosure run is never "
            "presented as oracle verification",
            "any per-division deity/label payload (VargaClassification carries only "
            "D-sign, division index, and fraction; deity output is out of scope, "
            "mirroring D24/D40/D45's own identical treatment - ADR-0089 section 4)",
            "the three non-default PyJHora chart_method variants (Parivritti Even "
            "Reverse, Parivritti Cyclic, Somanatha Parivritti Alternate) - excluded, "
            "mirroring D24's own two and D45's own three excluded PyJHora methods",
            "any non-parashara school variant",
            "any other varga; each requires its own ADR and certification",
            "no engine/ production module is created or modified by this certification",
            "paraphrase-only caveat: the BPHS citation is corroborated by consistent "
            "modern paraphrase across independent sources, not a located verbatim "
            "Sanskrit verse/Sarga-and-Shloka citation (ADR-0089 section 3, DP-032 "
            "section B.B)",
        ],
        "environment": {"python": sys.version.split()[0]},
        "preconditions": preconditions,
        "result": "PASS",
    }
    if _ORACLE_MISMATCHES:
        # Reached only when PyJHora actually ran. Every other gate has already
        # produced its evidence, so the non-blocking construction is honoured
        # and a real oracle disagreement still fails certification outright.
        report["result"] = "FAIL"
        support.emit(report, "VARGA_D16_V1_certification.json", "varga_d16", tee)
        fail(f"genuine oracle mismatches: {_ORACLE_MISMATCHES}")

    out = support.emit(report, "VARGA_D16_V1_certification.json", "varga_d16", tee)
    print("=" * 60)
    print("VARGA_D16_V1 CERTIFICATION (standalone rule, not production-registered)")
    print("=" * 60)
    for name, gate in report["gates"].items():
        print(f"{name}: {gate}")
    print("archived          :", out.relative_to(ROOT).as_posix())
    print("RESULT            : PASS")


if __name__ == "__main__":
    main()
