"""VARGA_D40_V1 CERTIFICATION RUNNER (ADR-0087).

Certifies the RATIFIED D40 (Khavedamsa) methodology (ADR-0087 selection and
frozen methodology). Per the owner's "CEO AUTHORIZATION - D40 certification
design/execution" instruction, no production engine module is authorized
this task.

**This file is NOT engine/astrology/varga_d40.py and does not create,
modify, or register anything under engine/astrology/varga_registry.py.**
The frozen D40 rule is instantiated here as a standalone, UNREGISTERED
`CyclicVargaRule` object and classified via the already-certified generic
framework (`engine.astrology.varga_classifier.classify`, `engine.astrology.
varga_rules.CyclicVargaRule` - pure functions/dataclasses exercised by
seven already-certified vargas, D2/D3/D7/D12/D24/D30/D45, with no registry
coupling), mirroring exactly the precedent already used for D24's own
certification-execution stage (ADR-0083, before its own later, separately-
authorized production-implementation task).

Regenerates certification/VARGA_D40_V1_certification.json FROM SCRATCH on
every run; the stored JSON is never accepted as proof.

Gates (ADR-0087, mirroring D24's own certification-design discipline):

A table/constant integrity (the frozen base/direction table, content-hash
pinned); B dense mathematical sweep vs an independently coded classical
reference; C corroboration disclosure (PyJHora's own published source was
read directly during DP-031 section J - see ADR-0087 section 3 - but
cannot be executed in this local environment; genuine oracle execution
remains deferred to this project's own CI hash-pinned oracle environment -
this certification-execution task does NOT wire certify_d40.py into CI,
exactly as D24's own ADR-0083 required that remain a separate, not-yet-
authorized act); D isolation (confirms this certifier touches no existing
engine/ file and the standalone rule is never registered); E independent
validator (validate_d40_holdout.py, a from-scratch reimplementation
importing nothing from engine.astrology); F boundary cases (sign-
transition edges; the exact internal division boundaries, empirically
confirmed representable with zero floor-classification effect - ADR-0087
section 3); G protected holdout (independent of the boundary cases, never
used for tuning); H negative controls (a real planted violation, confirmed
detected, confirmed the original standalone object remains unmutated); I
static independent-reference regression (STATIC values frozen from
validate_d40_holdout.py's own from-scratch reference_d40(), never
regenerated by this certifier's own rule at certification time).

No third-party computational oracle is used this execution. PyJHora is not
invoked: this project's own local PyJHora environment remains degraded
(numpy import failure, an already-disclosed, unchanged limitation). ADR-0087
section 3 records that PyJHora's own published source (`naturalstupid/
PyJHora`, GitHub) was read directly during DP-031 section J and its
default/Traditional-Parasara `khavedamsa_chart()` method matches this
frozen construction exactly - read-only corroboration, not executed oracle
agreement.

Exit code 0 = PASS, 3 = FAIL.
"""

import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

sys.path.insert(0, str(ROOT / "scripts"))
import certification_support as support  # noqa: E402

from engine.astrology.varga_classifier import classify  # noqa: E402
from engine.astrology.varga_rules import CyclicVargaRule, rule_content_sha256  # noqa: E402

#: Frozen exactly as ADR-0087 section 3 states it: odd source signs
#: (0-based Aries=0, Gemini=2, Leo=4, Libra=6, Sagittarius=8, Aquarius=10)
#: start from Aries (index 0); even source signs (Taurus=1, Cancer=3,
#: Virgo=5, Scorpio=7, Capricorn=9, Pisces=11) start from Libra (index 6);
#: forward counting (direction +1) for all twelve. A standalone object -
#: never registered via engine.astrology.varga_registry.register_varga_rule.
_ODD_SOURCE_SIGNS = frozenset({0, 2, 4, 6, 8, 10})
_ARIES, _LIBRA = 0, 6

D40_KHAVEDAMSA = CyclicVargaRule(
    divisions=40,
    start_sign=tuple(_ARIES if s in _ODD_SOURCE_SIGNS else _LIBRA for s in range(12)),
    direction=(1,) * 12,
)

#: Content fingerprint of the frozen rule above, pinned as a literal
#: hardcoded value from a prior intentional run (NOT computed from itself,
#: which would trivially always match and defeat the point of a pin -
#: mirrors scripts/certify_d24.py's own CERTIFIED_D24_CONTENT_SHA256
#: pattern exactly). Computed once via rule_content_sha256(D40_KHAVEDAMSA)
#: and verified independently before being pinned here.
CERTIFIED_D40_CONTENT_SHA256 = (
    "056e3e8af182568e9e2eaa5a1f54d86c40f7d97a53ece610f1e3105eb7a41006"
)


def fail(message):
    print("D40 CERTIFICATION FAIL:", message)
    sys.exit(3)


def _independent_d40_sign(source_sign: int, degree_in_sign: float):
    """Independently coded reference (ADR-0087 section 3), not imported from
    the rule under test - only the classical odd/even description is used,
    re-derived from first principles. Applies the engine's own documented
    boundary-promotion rule on its own terms (re-derived, not imported), so
    this checks whether classify() correctly IMPLEMENTS the documented
    convention, not a self-comparison."""

    segment_width = 30.0 / 40.0
    segment_index = int((degree_in_sign + 1e-10) / segment_width)
    if segment_index > 39:
        segment_index = 39
    start = _ARIES if source_sign in _ODD_SOURCE_SIGNS else _LIBRA
    return (start + segment_index) % 12, segment_index


def gate_a_table_integrity():
    if D40_KHAVEDAMSA.divisions != 40:
        fail("divisions != 40")
    for source in range(12):
        expected = _ARIES if source in _ODD_SOURCE_SIGNS else _LIBRA
        if D40_KHAVEDAMSA.start_sign[source] != expected:
            fail(f"sign {source}: start {D40_KHAVEDAMSA.start_sign[source]}, expected {expected}")
        if D40_KHAVEDAMSA.direction[source] != 1:
            fail(f"sign {source}: direction")
    return {
        "cells": 12,
        "mismatches": 0,
        "content_sha256": rule_content_sha256(D40_KHAVEDAMSA),
        "disclosure": "odd source signs (0-based 0,2,4,6,8,10) start Aries (index 0); "
                       "even source signs (1,3,5,7,9,11) start Libra (index 6); "
                       "forward counting for all twelve - Parashara/BPHS, DP-031 section J "
                       "(ADR-0087 section 3)",
    }


def gate_b_dense_sweep():
    mismatches = 0
    points = 51429
    step = 360.0 / points
    for i in range(points):
        longitude = i * step
        result = classify(longitude, D40_KHAVEDAMSA)
        source = int(longitude // 30.0)
        degree = longitude - source * 30.0
        expected_sign, expected_division = _independent_d40_sign(source, degree)
        if (result.d_sign, result.division_index) != (expected_sign, expected_division):
            mismatches += 1
    if mismatches:
        fail(f"dense sweep mismatches: {mismatches}")
    return {"points": points, "mismatches": 0}


def gate_c_corroboration_disclosure():
    return {
        "oracle_executed": False,
        "reason": "PyJHora unavailable in this local environment (numpy import failure, "
                  "an already-disclosed, pre-existing limitation) - genuine oracle "
                  "execution deferred to this project's own CI hash-pinned oracle "
                  "environment, per every oracle-tier certifier's own established pattern.",
        "read_only_corroboration": "PyJHora's own published source "
                  "(naturalstupid/PyJHora, GitHub, khavedamsa_chart()) was read "
                  "directly during DP-031 section J (ADR-0087 section 3): its default/"
                  "Traditional-Parasara method (odd_base=0/Aries, even_base=6/Libra, "
                  "both forward) matches this frozen construction exactly. This is "
                  "read-only source inspection, not executed oracle agreement.",
        "classification": "disclosed_gap_not_correctness_evidence",
    }


def gate_d_isolation():
    import ast
    import inspect

    this_module = sys.modules[__name__]
    own_source = inspect.getsource(this_module)
    tree = ast.parse(own_source)
    for node in ast.walk(tree):
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            module_name = getattr(node, "module", None) or (
                node.names[0].name if isinstance(node, ast.Import) else None
            )
            if module_name and (
                "varga_d40" in module_name or "varga_registry" in module_name
            ):
                fail(f"certify_d40.py imports {module_name} - must remain standalone, "
                     f"never touch the registry")

    if not (ROOT / "engine" / "astrology" / "varga_d40.py").exists():
        registered = True
    else:
        fail("engine/astrology/varga_d40.py already exists - certification design/"
             "execution does not authorize production implementation")
    return {
        "certifier_never_imports_varga_registry_or_varga_d40": True,
        "engine_astrology_varga_d40_absent": registered,
        "content_sha256_matches_pinned": rule_content_sha256(D40_KHAVEDAMSA) == CERTIFIED_D40_CONTENT_SHA256,
    }


def gate_e_independent_validator():
    import subprocess
    result = subprocess.run(
        [sys.executable, str(ROOT / "validate_d40_holdout.py")],
        capture_output=True, text=True)
    if result.returncode != 0 or "ALL INDEPENDENT D40 CASES PASSED" not in result.stdout:
        fail(f"independent validator failed: {result.stdout[-1200:]} {result.stderr[-800:]}")
    return {"result": "PASS",
            "classification": "corroborating_correctness_evidence",
            "note": "separate-process, from-scratch reimplementation; does not import "
                    "engine.astrology.varga_classifier, engine.astrology.varga_rules, "
                    "or this certifier's own D40_KHAVEDAMSA object"}


def gate_f_boundary_cases():
    import math
    cases = 0
    mismatches = 0
    width = 30.0 / 40.0
    for sign in range(12):
        for k in range(1, 40):
            exact_boundary = k * width
            cases += 1
            result = classify(sign * 30.0 + exact_boundary, D40_KHAVEDAMSA)
            expected_sign, expected_division = _independent_d40_sign(sign, exact_boundary)
            if (result.d_sign, result.division_index) != (expected_sign, expected_division):
                mismatches += 1
    for sign in range(12):
        # Mirrors D24/D45's own corrected boundary-probe construction
        # (ADR-0083 gate F): computed at the target magnitude directly, not
        # via an addition that can round away the intended epsilon.
        near_end = classify(math.nextafter((sign + 1) * 30.0, -math.inf), D40_KHAVEDAMSA)
        start = classify(sign * 30.0, D40_KHAVEDAMSA)
        cases += 2
        if near_end.division_index != 39:
            mismatches += 1
        if start.division_index != 0:
            mismatches += 1
    if mismatches:
        fail(f"boundary case failures: {mismatches}/{cases}")
    return {"cases": cases, "mismatches": 0,
            "convention": "engine-wide 1e-10 tolerance-promoted boundary convention "
                           "(longitude_utils.py), unmodified; no D40-specific exception - "
                           "cell width 30/40=0.75deg is exactly representable in IEEE-754 "
                           "double precision (ADR-0087 section 3), zero floor-"
                           "classification effect, identical clean result to D24's own"}


def gate_g_protected_holdout():
    mismatches = 0
    count = 0
    step = 0.0137
    longitude = 0.0
    while longitude < 360.0:
        source = int(longitude // 30.0)
        degree = longitude - source * 30.0
        result = classify(longitude, D40_KHAVEDAMSA)
        expected_sign, expected_division = _independent_d40_sign(source, degree)
        if (result.d_sign, result.division_index) != (expected_sign, expected_division):
            mismatches += 1
        count += 1
        longitude += step
    if mismatches:
        fail(f"protected holdout mismatches: {mismatches}")
    return {"points": count, "mismatches": 0,
            "methodology": "prime-step deterministic sampling, independent of gate B/F "
                            "points, never used to tune the frozen rule"}


def gate_h_negative_controls():
    from dataclasses import replace

    controls = []

    mutated = replace(D40_KHAVEDAMSA, start_sign=(1,) + D40_KHAVEDAMSA.start_sign[1:])
    detected = mutated.start_sign[0] != D40_KHAVEDAMSA.start_sign[0]
    controls.append({"control": "start_sign[0] mutated Aries->wrong value", "detected": detected})
    if not detected:
        fail("negative control 1 did not detect the planted mutation")

    mutated_dir = replace(
        D40_KHAVEDAMSA,
        direction=D40_KHAVEDAMSA.direction[:1] + (-1,) + D40_KHAVEDAMSA.direction[2:],
    )
    test_longitude = 30.0 + 7.0  # within Taurus (even, source=1), segment index != multiple of 12
    mutated_result = classify(test_longitude, mutated_dir)
    original_result = classify(test_longitude, D40_KHAVEDAMSA)
    detected_2 = mutated_result.d_sign != original_result.d_sign
    controls.append({"control": "direction[1] mutated +1->-1", "detected": detected_2})
    if not detected_2:
        fail("negative control 2 did not detect the planted mutation")

    original_hash = rule_content_sha256(D40_KHAVEDAMSA)
    mutated_hash = rule_content_sha256(mutated)
    detected_3 = mutated_hash != original_hash
    controls.append({"control": "content hash changes on mutation", "detected": detected_3})
    if not detected_3:
        fail("negative control 3 did not detect the planted mutation")

    restored_hash = rule_content_sha256(D40_KHAVEDAMSA)
    if restored_hash != original_hash:
        fail("D40_KHAVEDAMSA itself was mutated - this must never happen (dataclass is frozen)")

    return {"controls": controls, "all_detected": True, "original_object_unmutated": True}


#: Static expected values (D-sign, division index), generated ONCE, offline,
#: from validate_d40_holdout.py's own from-scratch reference_d40() - never
#: by calling this certifier's own D40_KHAVEDAMSA/classify() at certification
#: time. The certification-integrity lesson (ADR-0079), applied from the
#: outset, not retrofitted: comparing LIVE production-style output against
#: values frozen from an independent implementation is genuine cross-
#: implementation agreement, never a self-comparison.
STATIC_HOLDOUT = [
    {"id": "H1_aries_early", "longitude": 3.7, "expected_d_sign": 4, "expected_division_index": 4},
    {"id": "H2_taurus_mid", "longitude": 47.3, "expected_d_sign": 5, "expected_division_index": 23},
    {"id": "H3_gemini_boundary_adjacent", "longitude": 91.25, "expected_d_sign": 7, "expected_division_index": 1},
    {"id": "H4_leo_late", "longitude": 133.9, "expected_d_sign": 6, "expected_division_index": 18},
    {"id": "H5_virgo_exact_division", "longitude": 178.125, "expected_d_sign": 7, "expected_division_index": 37},
    {"id": "H6_libra_mid", "longitude": 200.0, "expected_d_sign": 2, "expected_division_index": 26},
    {"id": "H7_sagittarius_early", "longitude": 259.5, "expected_d_sign": 2, "expected_division_index": 26},
    {"id": "H8_capricorn_mid", "longitude": 289.5, "expected_d_sign": 8, "expected_division_index": 26},
    {"id": "H9_pisces_late", "longitude": 341.9, "expected_d_sign": 9, "expected_division_index": 15},
    {"id": "H10_aries_exact_zero", "longitude": 0.0, "expected_d_sign": 0, "expected_division_index": 0},
]


def gate_i_static_reference_regression():
    cases = 0
    mismatches = 0
    for case in STATIC_HOLDOUT:
        result = classify(case["longitude"], D40_KHAVEDAMSA)
        cases += 1
        if (result.d_sign, result.division_index) != (case["expected_d_sign"], case["expected_division_index"]):
            mismatches += 1
            fail(f"static reference mismatch on {case['id']}: "
                 f"got=({result.d_sign},{result.division_index}) "
                 f"expected=({case['expected_d_sign']},{case['expected_division_index']})")
    return {"cases": cases, "mismatches": 0,
            "methodology": "LIVE certifier output (classify() + the standalone D40_KHAVEDAMSA "
                            "rule) compared against STATIC values frozen from validate_d40_"
                            "holdout.py's own from-scratch reference_d40() (never regenerated "
                            "by this certifier's own rule at certification time)",
            "classification": "correctness_evidence"}


def main():
    tee = support.start_transcript()
    preconditions = support.preflight()
    report = {
        "schema": "varga_d40_v1_certification",
        "adr": "ADR-0087",
        "supersedes_provisional_id": "NOTHING_AUTHORISED",
        "date": str(date.today()),
        "scope": (
            "D40 Khavedamsa, Parashara/BPHS variant, Traditional Parasara construction. "
            "Rule under certification is a STANDALONE, UNREGISTERED CyclicVargaRule "
            "instance embedded in this certifier - not engine/astrology/varga_d40.py, "
            "no production module is authorized or created this execution."
        ),
        "rule": {
            "kind": "standalone CyclicVargaRule instance embedded in this certifier "
                    "(scripts/certify_d40.py) - not a registered production rule",
            "divisions": 40,
            "school": "parashara",
            "construction": "odd source signs start Aries (index 0), even source signs "
                             "start Libra (index 6), forward counting for all twelve",
            "content_sha256": rule_content_sha256(D40_KHAVEDAMSA),
        },
        "oracle": gate_c_corroboration_disclosure(),
        "gates": {
            "A_table_integrity": gate_a_table_integrity(),
            "B_dense_sweep": gate_b_dense_sweep(),
            "C_corroboration_disclosure": gate_c_corroboration_disclosure(),
            "D_isolation": gate_d_isolation(),
            "E_independent_validator": gate_e_independent_validator(),
            "F_boundary_cases": gate_f_boundary_cases(),
            "G_protected_holdout": gate_g_protected_holdout(),
            "H_negative_controls": gate_h_negative_controls(),
            "I_static_reference_regression": gate_i_static_reference_regression(),
        },
        "explicit_non_claims": [
            "no oracle execution this run - PyJHora unavailable locally, deferred to CI; "
            "certify_d40.py is NOT wired into .github/workflows/ci.yml's oracle-tier "
            "loop by this certification-execution task - that remains a separate, "
            "not-yet-authorized act",
            "any per-division deity/label payload (VargaClassification carries only "
            "D-sign, division index, and fraction; deity output is out of scope, "
            "mirroring D24/D45's own identical treatment - ADR-0087 section 4)",
            "the three non-default PyJHora chart_method variants (Parivritti Cyclic, "
            "Even Reverse, Parivritti Alternate) - excluded, mirroring D24's own two "
            "and D45's own three excluded PyJHora methods",
            "any non-parashara school variant",
            "any other varga; each requires its own ADR and certification",
            "no engine/ production module is created or modified by this certification",
            "paraphrase-only caveat: the BPHS citation is corroborated by consistent "
            "modern paraphrase across independent sources, not a located verbatim "
            "Sanskrit verse/Sarga-and-Shloka citation (ADR-0087 section 3, DP-031 "
            "section J.1(D40) item 1)",
        ],
        "environment": {"python": sys.version.split()[0]},
        "preconditions": preconditions,
        "result": "PASS",
    }
    out = support.emit(report, "VARGA_D40_V1_certification.json", "varga_d40", tee)
    print("=" * 60)
    print("VARGA_D40_V1 CERTIFICATION (standalone rule, not production-registered)")
    print("=" * 60)
    for name, gate in report["gates"].items():
        print(f"{name}: {gate}")
    print("archived          :", out.relative_to(ROOT).as_posix())
    print("RESULT            : PASS")


if __name__ == "__main__":
    main()
